### ISSUE TITLE
Modern platform support

### ISSUE THREAD

**Issue by ieperen3039** [bjoernknafla/amp#7]
Will the project in its current state be compatible with the newest versions of Windows and other platforms?

This mainly considering this repo has seen no updates since 2010.

**Comment by bjoernknafla** [comment]
This software has never been really tested on Linux - so I would be surprised if it works out of the box.
Windows is well known for its astonishing backwards-compatibility, so I would expect things to still work. However, this software has not been used in non test-environments - there will be problems that have not been uncovered.

My advice is to not use this project as a foundation for a new project as there will be unexpected bugs and problems you do not want in a new project. Instead I’d use modern C++ threading primitives.
